Add pre-flight check test for whether docker and apptainer are even working
This tests our container with the three supported combinations of
Docker/CVMFS bind-mount, Docker/CVMFSEXEC, and Apptainer/CVMFS
bind-mount, but running simple commands instead of starting the whole
pilot machinery, which simplifies getting the results and going through
the output.

Also, there is one GHA step for all three tests, so even if the first
one fails, the rest run and we can see if they succeed.

diff --git a/.github/workflows/build-container.yml b/.github/workflows/build-container.yml
--- a/.github/workflows/build-container.yml
+++ b/.github/workflows/build-container.yml
@@ -67,6 +67,23 @@ jobs:
         run: |
           sudo ./tests/setup_cvmfs.sh
 
+
+      - name: Pre-flight checks
+        if: ${{ matrix.arch == 'amd64' }}
+        env:
+          CONTAINER_IMAGE: ${{ steps.build-image.outputs.timestamp-image }}
+        run: |
+          errs=0
+          sudo ./tests/test_inside_gha.sh docker bindmount "$CONTAINER_IMAGE" preflight || (( errs += 1 ))
+          echo '|'
+          sudo ./tests/test_inside_gha.sh singularity bindmount "$CONTAINER_IMAGE" preflight || (( errs += 1 ))
+          echo '|'
+          sudo ./tests/test_inside_gha.sh docker cvmfsexec "$CONTAINER_IMAGE" preflight || (( errs += 1 ))
+          echo '|'
+          echo "$errs tests failed overall"
+          exit $errs
+
+
       - name: Docker + CVMFS bindmount
         if: ${{ matrix.arch == 'amd64' }}
         id: test-docker-cvmfs
@@ -75,7 +92,8 @@ jobs:
         run: |
           sudo ./tests/test_inside_gha.sh docker \
                                           bindmount \
-                                          "$CONTAINER_IMAGE"
+                                          "$CONTAINER_IMAGE" \
+                                          pilot
 
       - name: Docker + cvmfsexec        
         if: ${{ matrix.arch == 'amd64' }}
@@ -85,7 +103,8 @@ jobs:
         run: |
           sudo ./tests/test_inside_gha.sh docker \
                                           cvmfsexec \
-                                          "$CONTAINER_IMAGE"
+                                          "$CONTAINER_IMAGE" \
+                                          pilot
 
       - name: Singularity + CVMFS bindmount
         if: ${{ matrix.arch == 'amd64' }}
@@ -99,7 +118,8 @@ jobs:
           else
               sudo ./tests/test_inside_gha.sh singularity \
                                               bindmount \
-                                              "$CONTAINER_IMAGE"
+                                              "$CONTAINER_IMAGE" \
+                                              pilot
           fi
 
       - id: upload-by-digest-harbor
